### ISSUE TITLE
Track my position option - enables phonetrack support?

### ISSUE THREAD

**Issue by mannp** [nextcloud/maps#111]
Great app, just installed it, so thanks :)

Not sure what the track my position option does and whether it enables your phonetrack app support?

Thanks for any insight and whether i still need phonetrack nextcloud app installed for the phonetrack android app to work?

Thanks

NC 16.04 Maps/Phontrack Android Latest 02/09

**Comment by jancborchardt** [comment]
@eneiluj as dev of both Maps and PhoneTrack can probably answer best about the current state of integration, and further plans. :)

**Comment by mannp** [comment]
@jancborchardt okay thanks @eneiluj I couldn't find anywhere what this option did in the Maps settings ... ?

**Comment by tacruc** [comment]
The checkbox just enables the tracking oft that specific browser.

**Comment by WNYmathGuy** [comment]
The "Your devices" will be cool when it's fleshed out. Like Firefox managed to place the computer I was using on the map sufficiently well, but the chrome browser with a different user logged in had no positioning despite the browser giving the webpage authority to know the location. The map for both users knows a position (via the pin icon above the +/- zoom controls), but the Chrome browser doesn't know a device being used.

I'm already using GPSLogger and OwnTracks on my mobile device and sharing with the family through Nextcloud, but the option for import devices just looks for files instead of picking up on the same sharing that I'm already doing in Nextcloud.

**Comment by eneiluj** [comment]
Hey there. I'm not very reactive these days...

There are basically two ways to log device positions in Maps:

* enable the checkbox in sidebar settings to regularly make the browser send its position to Maps. Browser user-agent is parsed and used to set device name
* use PhoneTrack-Android which is able to log to Maps with "Maps logjobs" but...it's disabled in latest release :grin:. I'll publish a new release (v0.0.13) soon with this new logjob type.

@WNYmathGuy I'm not sure I get your first point.
About the second one, are you suggesting it would be nice to be able to "see" PhoneTrack sessions in Maps?

**Comment by WNYmathGuy** [comment]
@eneiluj The first point was confusing because it was an edited thing. I was afraid to delete the original first paragraph, so I just wrote the new disclaimer in bold. I guess I should have deleted it instead.

So the final paragraph, yes I was thinking along the lines of having shared locations via the PhoneTrack app just propagating to the Maps app.

**Comment by Kariton** [comment]
@eneiluj This is just a realy nice NC app incl. PhoneTrack.

But is there still a point, in the future, to install PhoneTrack NC app?
Overal is 'maps'  just better, IMHO.

Besides the leak of "tracking abilities" (display, follow, fencing, etc.) - will they be implemented in this app?
Or do we rely on two differen apps?
ATM i dont realy get the point. I have now both. 'maps' for their features. and PhoneTrack for its features.
I love them both - but it feels kinda weird. ;)

**Comment by tacruc** [comment]
Phonetrack supports tracking to maps since a while
