### ISSUE TITLE
Discard or hide pictures with coordinates 0,0

### ISSUE THREAD

**Issue by myxor** [nextcloud/maps#119]
I encountered a few very old pictures in my collection which have 0,0 as coordinates in the EXIF dataset as can be seen here:

```
identify -verbose picture.jpg
[...]
    exif:GPSInfo: 2222
    exif:GPSLatitude: 0/1, 0/1, 0/1
    exif:GPSLatitudeRef: N
    exif:GPSLongitude: 0/1, 0/1, 0/1
    exif:GPSLongitudeRef: E
    exif:GPSVersionID: 2, 2, 0, 0
[...]
```

These pictures are shown in the Atlantic ocean (where long = 0 and lat = 0 is):

![image](https://user-images.githubusercontent.com/1397377/64232528-65fd0900-cef2-11e9-8dce-ca07cceec903.png)

Is it possible to hide these pictures as they are obviously not placed correctly?

**Comment by tacruc** [comment]
Right now you can remove the pictures with an right click on them. There you have the opportunity to move them to the right place. If we wouldn't show them, you would not know that you have "broken" pictures.

**Comment by jancborchardt** [comment]
I’d a gree with @myxor that they should be hidden. Having 0,0 coordinates is basically the same as having no coordinates at all, and it doesn’t necessarily mean they are broken, maybe just taken with a strange device?

**Comment by v1r0x** [comment]
Even if it is just very **very** unlikely to have a picture from 0, 0 (e.g. snorkeling trip :grin:): 
From a developers side it is odd to exclude correct values just because they could also be faulty.
From a users perspective it might be confusing that these picture(s) are hidden because of this.

I'd suggest
a) adding additional tests (I don't know if there are other exif fields indicating that a picture has no/a faulty gps position) or 
b) show an information that X images are hidden, because they might have wrong exif data. And allow the user to show them again

**Comment by eneiluj** [comment]
On this very subject of 0,0 coordinates, I would prefer to avoid adding interface elements which would potentially bring confusion to the users and make the code harder to maintain. We could just make a choice to show or hide them.

I think it makes sense to hide them as having such coordinates is pretty much the same as not having any... I assume users don't care about knowing which pictures have such coordinates.

**Comment by jancborchardt** [comment]
Would agree with @eneiluj here, let’s keep it simple. Even if we do hide it in the first step, we can still do other stuff later. (Emphasis on "later". :)

**Comment by matiasdelellis** [comment]
![imagen](https://user-images.githubusercontent.com/733715/71355825-fffac700-255e-11ea-86f7-6d63aa44fc21.png)

Please, although I would like to have a way to geolocate them in a batch. At least we must hide them. :disappointed:

**Comment by tacruc** [comment]
v0.2.0 hides 0.0 coordinates
