### ISSUE TITLE
"Media scan was not done yet" .. ?

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/maps#128]
I just installed the app and I'm not familiar with it that much yet. But when I run & access it, this is what I see:
```
Media scan was not done yet. Wait a few minutes/hours and reload this page to see your photos/tracks.
Failed to load contacts

```
It's been 10+ hours and nothing has changed. I also tried running OCC scan.

The log outputs additional error:

![Screenshot_1](https://user-images.githubusercontent.com/36133540/64262010-bb0a4080-cf2d-11e9-9458-7aae36cd5baa.png)

I use Nextcloud (15) snap package.

**Comment by tacruc** [comment]
Which version did you install? Did you have version 1.1 installed before?

**Comment by pilsnerbeer** [comment]
- Version 0.1.2
- I didn't have 1.1 installed before
- I use cron
- Only a handful of pics, Im guessing under 100.

**Comment by Twilek-de** [comment]
I am also seeing this. This message always shows for a couple of seconds, althought the scan should be complete and pictures are showing.

**Comment by gpgmailencrypt** [comment]
I'm having the same problem. My photo collection is rather big, but there was no progress in filling the database table 'maps_photos'  for days. So I tried out updating manually with 
./occ   maps:scan-photos

This stops after a while adding a few pics with a simple "Killed" on command line, no further error message.

I use version 0.1.2

**Comment by FelixBuehler** [comment]
Got the same problem. Did run occ maps:scan-photos and it immediately threw an PHP Memory Memory error. So I started it again with a memory_limit of 1024M. Now it's running. Will probably need some hours/days, since my cloud is pretty big.

**Comment by tacruc** [comment]
@eneiluj 
I think we have two problems here:

- The commands  maps:scan-photos and  maps:scan-tracks do not change the inital scan status, such that the message will show forever, if the inital scan failed, for whatever reason.
  - I'm not shure which is the right command to update the status. With the tracks or with the photos scan? Or add a new command which runs both and updates the initial scan status?
- For new created users the status is not set or updated.

**Comment by marcuseric** [comment]
I've got a related problem hence I didn't want to create a new issue as the cause might be related.

When I installed maps I got the same message as above stating that the media scan wasn't done yet. When refreshing the site again, this message doesn't popup again. I've got round about 35GB of photos stored in my folders. Every now and then some (approx. 5-20 pictures) get added to the map, but there is no significant progress. I tried `./occ maps:scan-photos` as mentioned above, but the prompt responds this:

> `occ $ maps:scan-photos`
> `Encryption is enabled. Aborted.`

My files are encrypted, yes. How can it be that some files could have been scanned, but the most haven't? Encryption is enabled for the whole account/ instance. Isn't it possible that the files are scanned anyway if the scan trigger is issued by the corresponding user?

Thanks in advance for your help - any explanation is very appreciated :)

**Comment by AlfredSK** [comment]
Concerning the error message about enabled encryption. I get it too.
But I have only installed/enabled server-side encryption. But I have _not enabled_ the encryption of the home storage. So, from my understanding, the photo scan should work - but it doesn't.

**Comment by eneiluj** [comment]
@tacruc About updating the status when scanning is done by calling the occ commands: Even if it's a bit dirty, we can set the first-scan status to OK even if only one scan was done (photos or tracks) because once the admin runs one scan, he/she will most likely run the other. So it becomes simple to us, just set the status to OK at the end of any scan made with occ.

About newly created users, this is a stupid mistake (from me :laughing:). A simple way to solve it would be to consider the state only when it has a value. Currently, no value is considered as "false". We would only need to set the first-scan value to "false" for all existing users. This way new users would not have any value for this and would not see the warning. What do you think?

About the error described by @pilsnerbeer, it's because NC 15 API does not include `OC\ContactsManager::getUserAddressBooks()` as described [here](https://docs.nextcloud.com/server/16/developer_manual/api/OC/ContactsManager.html?highlight=contactsmanager#OC\ContactsManager::getUserAddressBooks)
We should therefore raise minimum NC version to 16.

**Comment by Friptick** [comment]
This is my problem too. Blocking everything else until resolved. However, is it even necessary to scan photos by default? Personally the only thing I want available is GPX, which obviously is tiny by comparison to photo media.

**Comment by alexanderdd** [comment]
I also still have this problem "Media scan was not done yet" shows forever.. 
Maps 0.1.10, Nextcloud 22.2.5
