### ISSUE TITLE
Getting media scan message every time

### ISSUE THREAD

**Issue by gucu** [nextcloud/maps#184]
I installed the app several days ago and I get the media scan message everytime. So far it has scanned 12 contacts, no photos and some gps files. It is very slow.
Operating system: Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64

Webserver: Apache (cgi-fcgi)

Database: mysql 10.3.18

PHP version: 7.2.23

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, cgi-fcgi, ctype, curl, dom, mbstring, fileinfo, ftp, gd, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, SimpleXML, sqlite3, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, imagick, Zend OPcache

Nextcloud version: 16.0.5 - 16.0.5.1

Do you want to see the full server configuration?

**Comment by toast1234** [comment]
Same for me. The external mounts are not scanned. Maybe that's related? would be good if external mounts are scanned. Or even better it you could select what folders should be included in Maps.

**Comment by flow7** [comment]
Similar here, I installed Maps (which I love) 3 days ago, and this is currently shown on the map:

- My favourites - no problems, just 3 locations I marked
- 245 contacts - every time I look Maps seems to have located another few.
- Photos: 12 - interestingly only those 12 pictures I took and had uploaded from my phone through Nextcloud sync since the Install of Maps 
- Tracks - none yet, even though there are a couple in my folders

Will Maps only locate newly uploaded files? Thanks

**Comment by gucu** [comment]
Just going to run the OCC command suggested by @flow7 and let you know how it went. Up to 64 photos and 12 contacts!

**Comment by jancborchardt** [comment]
@eneiluj @tacruc any other system information that would be useful for debugging?

@flow7 @toast1234 I guess at least some details about your system like versions, enabled apps or funcationality etc (like external storages) would be good. :)

**Comment by gucu** [comment]
@flow7 I ran the OCC maps:scan-photos and nothing happens! there is no feedback. Should there be please?

**Comment by toast1234** [comment]
My setup:
Nextcloud 17.0.0
Debian 9.11
PHP 7.3.10
MariaSQL 10.4.8
Nginx 1.17.4-1~stretch
Maps 0.1.2
External storage support	1.8.0

I have NFS mounted my photo album and it is added to Nextcloud as a Local External Storage mount (the Local External Storage is created by admin and accessed by all user of the group)
Running "occ maps:scan-photos" scan all folders except the external mount.
This is sort of the opposite of what I want as it will add a lot of images from various other directories instead of the "real" photo album folder...

**Comment by HammyHavoc** [comment]
Is there a way to disable media scanning or only allow it for selected directories? Running it globally doesn't make a lot of sense.
