### ISSUE TITLE
Navigaton with OSRM wont work

### ISSUE THREAD

**Issue by corincorvus** [nextcloud/maps#208]
Hi,
i installed via docker image a OSRM Server.

now i tried to input the urls. it wont work.
![2019-11-04 19_15_14-Einstellungen - C-Lab Cloud](https://user-images.githubusercontent.com/21257329/68147261-fd55fb00-ff39-11e9-83a9-481d592309de.jpg)
![2019-11-04 19_15_23-Karten - C-Lab Cloud](https://user-images.githubusercontent.com/21257329/68147266-fe872800-ff39-11e9-90ed-c98f8728663b.jpg)

URL work: https://docker.c-lab.one/osrm/route/v1

any idea?

**Comment by tacruc** [comment]
Is any error in the browser console?

**Comment by corincorvus** [comment]
No :/

**Comment by gary-kim** [comment]
Just to confirm, have you tried navigation? You can ignore the message saying that there are no routing engines set up.

**Comment by corincorvus** [comment]
Yes i tried :/

i will test it this weekend.

**Comment by corincorvus** [comment]
Navigation dont work.

How i test the Server itself? I only found a curl command and it was fine.
"curl "http://127.0.0.1:5000/route/v1/driving/13.388860,52.517037;13.385983,52.496891?steps=true""

![2019-12-13 11_36_15-Karten - C-Lab Cloud](https://user-images.githubusercontent.com/21257329/70797584-16f22a00-1da5-11ea-9573-cd024523f059.png)

**Comment by dd86k** [comment]
I tried setting it up on the same instance, but I'm unaware if the client itself (JS) or if the server (back-end/php) communicates with osrm-routed.

**Comment by dd86k** [comment]
I somehow made it work. I figured the Web JS client makes the requests to the server, so I checked my server config.

I have an osrm-routed instance running on my own instance, and had to ensure that nginx (in my case) was listening to 5000 because the configured server is effectively `https://example.org:5000/route/v1` (so `listen 5000 ssl` in my case).

Then, on nginx, for my nextcloud instance, I verified the CORS header is enabled (I did under the server clause with `add_header 'Access-Control-Allow-Origin' '*';`).

Then for my osrm instance, I did my passthrough like this:
```
location / {
	proxy_pass              http://127.0.0.1:4990;
	proxy_redirect          off;
	proxy_set_header        Host $host;
	proxy_set_header        X-Real-IP $remote_addr;
	proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_connect_timeout   150;
	proxy_send_timeout      100;
	proxy_read_timeout      100;
	proxy_buffers           4 32k;
	client_max_body_size    500m; # Commit size
	client_body_buffer_size 512k;
}
```

Hope that helps for future people going through this Issue. Lots of traps that new people could make.

![image](https://user-images.githubusercontent.com/8390674/72949003-fbd7ea00-3d54-11ea-91f0-02822647d880.png)

**Comment by corincorvus** [comment]
i will test it today. thank you :)

**Comment by corincorvus** [comment]
At the Moment i cant test "Maps". Iam on 17.0.2-0 and services like cron dont work, if i enable Maps.
In nextcloud community they have the same problem.
https://help.nextcloud.com/t/cron-php-call-to-a-member-function-getuserfolder-on-null/69899/6

**Comment by dd86k** [comment]
I can also confirm on my side, but I think that's another issue of its own, where the devs will likely encourage you to create a new Issue.

**Comment by Happyfeet01** [comment]
i setup osrm-backend and frontend with docker, but navigation won´t work. 

Nextcloud Maps tells me: **Streckenfehler: undefined**

**Comment by bloodhunterd** [comment]
Even though the last post was almost a year ago, but the issue is still open.

I run Nextcloud (Docker) and tried to set up Maps with the OSRM Backend (also Docker). I figured out that the routing requests are executed directly via JavaScript, so that an internal solution isn't possible and the Port 5000 has to be open on the server. My suggestion is that the routing request are send against Nextcloud and the Maps app will do the actual call agains the OSRM server.

**Comment by pwepwe973** [comment]
hello a solution has been found for these few years??

**Comment by corincorvus** [comment]
No
