### ISSUE TITLE
Nextcloud 18 release

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#226]
We should get an updated release which is supporting NC18. 
@nextcloud/maps What needs to be done?

- [x] #195
- [ ] #217 
- [x] #232
- [x] #234

**Comment by nursoda** [comment]
Hi Jan, the app store says that 0.1.4 is for NC17 and NC18. I'm on NC18RC2 (and don't get an update to NC18release). I was notified to update Maps 0.1.2 to 0.1.4 – but when doing so, it says that it couldn't. When accessing app details in settings/apps (right sidebar), it there says that it requeres NC17 or lower. So I uninstalled maps, and it won't reinstall, error is "Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden. Die App konnte nicht aktualisiert werden."

**Comment by mattsches** [comment]
@nursoda I'm having the same issue when trying to update `maps` in the admin backend. The reason seems to be a request timeout while downloading the release (it just takes too long to download):

`GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 29918 milliseconds with 5187147 out of 24306414 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

So this might be a general NC problem, because download the release works locally. I don't know if there is a setting anywhere to increase the timeout.

Come to think of it, a more probably reason is the [`max_execution_time` PHP setting](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time) which defaults to 30 seconds. So try to change that in your `php.ini` configuration file.

An alternative approach that worked for me is updating the app using `occ` because on the command line there is no default time limit:

```
$ sudo -u www-data php ./occ app:update maps
```

**Comment by nursoda** [comment]
I think the issue with 0.1.4 rather is https://github.com/nextcloud/maps/issues/240

And I already increased the NC-internal timeout to be able to download the onlyoffice community edition app (which is much larger). Since that worked, php.ini either already was increased before or isn't an issue here.

**Comment by mattsches** [comment]
Fair enough, seems to be two separate issues then.
