### ISSUE TITLE
PageController tests failing / questions

### ISSUE THREAD

**Issue by paulschwoerer** [nextcloud/maps#233]
I noticed the PageController tests failing in the master branch, due to a missing parameter. This would be quite easy to fix and I'd like to open a PR, however I'm not quite sure how the PageController is used in NC. I can't find an instantiation in the Maps App Code. How does NC 'know' which parameters to pass to the PageController? @eneiluj @tacruc

**Comment by tacruc** [comment]
It's some time ago I worked with this. I guess you can find some information here:
https://docs.nextcloud.com/server/13/developer_manual/app/classloader.html.
@juliushaertl do you have good additional information?

**Comment by juliushaertl** [comment]
Some of them are injected depending on their name, like `$userId`, the others are based on the class that is defined as a type hint. https://docs.nextcloud.com/server/13/developer_manual/app/container.html has some more details although the 13 version I've linked is a bit outdated (but the stable one is unfortunately not reachable atm), since you don#t need to register a service for your classes anymore. That is done automatically for classes in your apps namespace.

**Comment by paulschwoerer** [comment]
Thanks for your input, it's a lot clearer now. I'll open a PR
