### ISSUE TITLE
Bigger Hint to not execute maps:scan-* on a regular basis

### ISSUE THREAD

**Issue by tacruc** [nextcloud/maps#362]
I have the feeling that every second issue includes the description that people run maps:scan-images in a cronjob or manually, whenever they upload pictures. 

This command has high computational cost. On my instance it creates background jobs which run for multiple days. This is not a problem if the command is exectued once, if there is an problem with the existing database, or when the app was installed (it might be executed automatically). But it is not designed to be executed on a regular basis, not even once a month.

**Comment by akrea** [comment]
OK, but how and how often is it triggered by the app?

**Comment by akrea** [comment]
My initial scan shows only about 2k pics. My wife's (user) map with the same pic folders (shared in NC) has >13k pics...

**Comment by Galbar** [comment]
FYI, I'm forced to run the scan-* jobs frequently because my images/tracks are not automatically added to the maps app because, from what I've gathered from the various issues I've found here, I'm using S3 as (the only) storage backend.

I've used this app for a while now. I'm following a couple of issues relating to this. I still don't understand why the issue has not been addressed. I tried to take a look a few months ago but I am not familiar at all with how NC and the maps app are structured.

Is there, at least, any suspects of what may be causing the issue?

**Comment by tacruc** [comment]
I'm aware that the situation is far from optimal. I summarized a possible outlook in #552, which would make this process more modular and therefore easier to change, which implementation will work in practice. It additionally allow to have different implementations, with different pros and cons, such that there might be an implementation for each setup and we don't need one implementation to work on every setup.
