### ISSUE TITLE
Add notes to map

### ISSUE THREAD

**Issue by gitaarik** [nextcloud/maps#414]
Hey guys,

First of all, very nice app! I would love to start using this as a personalized maps system.

At the moment you can add to the map:

- favorites
- photos
- contact address

But there's not really a way to add notes to places. If you favorite them you can add a note in the favorite, but I don't necessarily want to add the place as a favorite, I just want to add a note about it. For example, a Wi-Fi password.

Also, if I save an address as address of a contact of mine, I would like to add a note to that place. I don't want to have 2 pointers (1 for the contact and 1 for the note).

How do you guys think about this, what are the possibilities? I would like to give it a try to develop.

**Comment by tacruc** [comment]
Can you be more presice do you want a new element called notes to show on the map? 

If yes how would it be different to a favorite in the category notes?

Or do you want the ability to add a note to different kind of already existing objects?
Because there are different possibilities. For Pictures you can add a comment, in the sidebar of the picture view. 
For favorites there is a note field.
For contacts you can write the note in the contact, via the contacts app, it could be shown then.
For tracks and devices I'm unshure.

Or is it more about combining tow markers of different objects to one marker on the map?

**Comment by gitaarik** [comment]
I have been thinking about it and I think it would work nice like this:

- You can create categories for favorites, so you can organize and filter your favorites.
- It would be nice to be able to make a specific address a favorite, and also to connect it to a contact, and add photos etc. To be able to combine them all on one point indeed.

It would be nice for the following use cases:

- You want to favorite your parents house, add a note about the Wi-Fi passwords, and connect their contact cards all on the same address. 
- You want to make a list of nightshops in your town, in a separate category, so you can filter them out when you don't need them. Also you want to add notes to each nightshop about their opening times. The times on public maps are never correct.
- You are making a trip and you want to add memories of places you have been. You want to add notes and photos, and you want them all to be in a specific category. Also you might connect some contacts to addresses you've been.

What do you think?

**Comment by gitaarik** [comment]
I am just realizing now that you already have categories for favorites. I didn't realize that before, and it wasn't clear how to create a new category, but I got it now. When you add a new favorite you can create a new category.

So that's great! So I just want to be able to add multiple items to a specific address. Contacts, favorites, photos, etc.

**Comment by meichthys** [comment]
> it wasn't clear how to create a new category

I have to relearn the process of creating a new maps category each time i use the app lol 🤣
