### ISSUE TITLE
Release version for Nextcloud 20

### ISSUE THREAD

**Issue by vwbusguy** [nextcloud/maps#444]
The current version of Nextcloud Maps was released 6 months ago and and several fixes and updates have been merged in that time.  Would it be possible to cut a new release and consider a more frequent, perhaps monthly, release cycle?

**Comment by raimund-schluessler** [comment]
Since NC 20 is around the corner, a version of Maps actually supporting NC 20 is necessary. I adjusted the title accordingly.

**Comment by Valdnet** [comment]
NC 20 RC2 version is out. Maybe you should think about the release of NC 20 compatible Maps.

**Comment by tacruc** [comment]
> NC 20 RC2 version is out. Maybe you should think about the release of NC 20 compatible Maps.

In general I'm a big fan of apps, which get published 2 to 4 weeks after the main release. Therefore I won't do anything until NC20 stable is released. :wink: 

No seriously, if you follow the PR you might see that we're working on it. Otherwise it's sufficient to like just the first request, if you don't have new significant input.

**Comment by TheRaven500** [comment]
Is the newest version on git only compatible with NC20? I have NC19 and it says it is not compatible.

**Comment by xoac** [comment]
So this issue should be closed? 0.1.8 is out.
