### ISSUE TITLE
Reinstalling the app doesn't recreate the database tables

### ISSUE THREAD

**Issue by beccon4** [nextcloud/maps#493]
My Maps app simply didn’t scan my photos - so I decided to make a clean reinstall. For that I dropped the oc_maps_* tables from the database, deleted the "maps" records from oc_appconfig and reinstalled the app. Unfortunately the install doesn’t recreate the tables in the database causing the app to fail. How can I recreate those tables? How does the install assume that the tables are present?

**Comment by unknownuser26** [comment]
i still have the same problem

**Comment by tacruc** [comment]
> For that I dropped the oc_maps_* tables from the database, deleted the "maps" records from oc_appconfig and reinstalled the app.
Maybe that was a stupid Idea, but as you are familar with sql I bet you can recreate those tables manually. 
We can not catch and programm workarrounds for manual interventions in the programmed logic. The tabels are not recreated as the migrations are only exectued once.
But you could allso apply more manuall modifications and hope that all turns out well. So you could try to fix the maps migration in the migration table, such that they are reexecuted. It might work and be a easy way to get those table back, or might do worse.

Or you could restore a backup before you deleted the tables.
