### ISSUE TITLE
Restrict app to groups

### ISSUE THREAD

**Issue by szaimen** [nextcloud/maps#507]
I've searched for existing issues, but didn't found one, hence I opened this one.

**Is your feature request related to a problem? Please describe.**
Hey, I would like to restrict some users to not be able to use the maps app. 

**Describe the solution you'd like**
I would like to be able to restrict the maps app to specific groups without using the guests app.

**Describe alternatives you've considered**
Currently no idea

**Additional context**
Here is a screenshot for the calendar app:
![image](https://user-images.githubusercontent.com/42591237/99199863-5f2e7f00-27a2-11eb-8dc9-5a6b080b2970.png)

There was a comparable problem with the contacts app. Maybe you could use the same fix for the maps app?
https://github.com/nextcloud/contacts/pull/1938
https://github.com/nextcloud/contacts/issues/1937

Alternatively, the photos app is capable of requesting all files without having the filesystem type in its appinfo.xml
https://github.com/nextcloud/photos/blob/master/appinfo/info.xml

**Comment by szaimen** [comment]
Maybe @eneiluj has an idea how to implement this? :)

**Comment by wronny** [comment]
not sure if this is still valid or not
https://docs.nextcloud.com/server/11.0/developer_manual/app/info.html#types
so might be related to types section in appinfo/info.xml
I tested in my test nextcloud instance the following:
1. disabled maps
2. removed the following lines in maps/appinfo/info.xml
`     <types>
         <filesystem/>
     </types>`
3. enabled maps

as a result I was able to limit maps to groups
<img width="256" alt="maps_limit_to_group" src="https://user-images.githubusercontent.com/3709024/104385319-530d3680-5533-11eb-86e3-c419a9845483.png">
as far as I can see maps is still working as expected and is only available for users of testgroup.
**However I have not really any knowledge about the reason and result of the defined filesystem type in info.xml and also not knowledge about possible consequences if removing this type. I only tested it due to curiosity and wanted to share this observation.**

**Comment by szaimen** [comment]
> 1. disabled maps
> 2. removed the following lines in maps/appinfo/info.xml
>   `     <types> <filesystem/> </types>`
> 3. enabled maps

@eneiluj do you know if that has any bad side effects?

**Comment by normen** [comment]
I can confirm that this is broken when installing the plugin on NextCloud 24 and that the fix above works to re-enable Group Restrictions.

**Comment by Thatoo** [comment]
Duplicate of https://github.com/nextcloud/maps/issues/170

**Comment by normen** [comment]
Thanks for the fix!
P.S. @tacruc - Arne is that you? Normen from Morsum here o_O

**Comment by rodinux** [comment]
> not sure if this is still valid or not https://docs.nextcloud.com/server/11.0/developer_manual/app/info.html#types so might be related to types section in appinfo/info.xml I tested in my test nextcloud instance the following:
> 
>     1. disabled maps
> 
>     2. removed the following lines in maps/appinfo/info.xml
>        `     <types> <filesystem/> </types>`
> 
>     3. enabled maps
> 
> 
> as a result I was able to limit maps to groups <img alt="maps_limit_to_group" width="256" src="https://user-images.githubusercontent.com/3709024/104385319-530d3680-5533-11eb-86e3-c419a9845483.png"> as far as I can see maps is still working as expected and is only available for users of testgroup. **However I have not really any knowledge about the reason and result of the defined filesystem type in info.xml and also not knowledge about possible consequences if removing this type. I only tested it due to curiosity and wanted to share this observation.**

I can't say if it's a a security issue, but it still works for me on a NC 27.0.1, thanks a lot !

**Comment by normen** [comment]
> I can't say if it's a a security issue, but it still works for me on a NC 27.0.1, thanks a lot !

Its not a security issue, afaik the issue is that if you do this then the background processing of data (image GPS data, GPS tracks etc.) won't be done.
