### ISSUE TITLE
Full picture not shown

### ISSUE THREAD

**Issue by smalchow** [nextcloud/maps#580]
Hi,

i tried to search the existing issues but i did not find one, however, this issue is hard to put a search that does not cover alot of other issues, so if there is already one issues, please excuse me.

I have the maps app running, pictures are scanned and previews are presented just fine on the map, if i open the side bar, i can also see the pictures and even flip through the with ">" and "<", however in the overlay the pictures are not shown, i checked the logfiles but could not find anything, if i copy the link that is called when trying to show the picture and put it into another browser windows, i am presented with the option to download.

Any ideas where to look.

My setup is docker-compose based with the official images and is updated to the latest version, if interesting, i runs on ubuntu 20.04

soeren

**Comment by tacruc** [comment]
I have problems, to understand the exact issue? Could you maybe post some, screenshots. I think this would make it a way easier to see exactly what you mean.

**Comment by PA3LIT0** [comment]
Hi,

I can also confirm that I have the same problem. I'm running Ubuntu 20.10 arm64. The problem is as follows. The images (and their previews) are normally displayed on the map but when I try to click the image to view it it loads forever (2nd image), nothing in the error log.

![image](https://user-images.githubusercontent.com/71569166/113295012-eca8e080-92f7-11eb-83c4-8d889470d602.png)

![image](https://user-images.githubusercontent.com/71569166/113295243-3db8d480-92f8-11eb-80b9-036d0573470b.png)

**Comment by tacruc** [comment]
Could it be #543?

**Comment by PA3LIT0** [comment]
Yes, thank you so much! :)

The problem has been fixed.

**Comment by smalchow** [comment]
Yes it is, thank you
