### ISSUE TITLE
Placing photos on the map takes extremely long

### ISSUE THREAD

**Issue by JakobMiesner** [nextcloud/maps#641]
Hello, I ran `maps:scan-photos` and it located all my 1000 Photos correctly.
But even now (48 hours later) I can only see 9 of my images on the map.
Is it supposed to be this slow and can I speed it up?

**Comment by JakobMiesner** [comment]
16 days later and only 101 photos are scanned.
I am running Nextcloud 22.0.0 with Maps 0.1.9 on my raspberry 4.
The raspberry should be fast enough, my previous setup with the same device and Nextcloud v21 worked fine.
Any ideas?

**Comment by benjaminsabatini** [comment]
Same problem. Also, nextcloud reports that cron has failed.

**Comment by ThatCoffeeGuy** [comment]
Same here.

**Comment by douardda** [comment]
Running "php -f cron.php" by hand (nc 21.0.3, maps 0.1.9) took something like 15 minutes but it did only scan something like 10k photos.
In fact each time the cron.php script is executed, it scans a few 1k photos more, but since it take a little less than 15mn to do so, I had to change the cron job delay to 15m to prevent from having multiple concurrent executions.

It took a few hours (more or less the nigh) to finally finish the job; the oc_maps_photos table has 151k rows but there are only 54k distinct file_id in there (shared photo directories are scanned for every user).

**Comment by andyxheli** [comment]
Yes, i agree it dose take a while to place the photos on the map and when clicking on the map tab it take about 15 to 30 seconds to show them. This should be instance and not have to wait once the photos are scared it should do some caching so it dose take forever to populate the photos on the map

**Comment by tacruc** [comment]
There are some improvement in #924 which can be tested in v0.2.5. I expect further improvements when the DAV metadata feature gets public.
