### ISSUE TITLE
Unable to install 0.2.0-2-nightly in combination with PHP 8.1

### ISSUE THREAD

**Issue by UweSauter** [nextcloud/maps#780]
When installing maps from inside Nextcloud v0.1.10 is downloaded and activated on my server running PHP 8.1.7.

Trying to manually install v0.2.0-lightly by downloading and extracting the package inside the "apps" file system directory I get a warning when trying to activate the addon inside Nextcloud. Error message is:

This app cannot be installed because the following dependencies are not fulfilled:
PHP with a version lower than 8.0 is required.

**Comment by tacruc** [comment]
PHP 8.1 is unfortunately not supported yet.
Working on it in #781

**Comment by rkkoszewski** [comment]
Well this issue broke my Nextcloud 24.0.3 installation. It complained during the upgrade that a version lower than PHP 8.0 is required, but it proceeded with the upgrade anyway. Now my whole Nextcloud instance is inaccessible as it keeps wanting to perform an update that it is never able to complete due to the max version constraint. All was working fine before the upgrade..

**Comment by tacruc** [comment]
You can either try the master branch which adds PHP 8.1 support. And you could file a bug report, with all the required information. That an app with unfulfilled requirements breaks the update.
